services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend